### ISSUE TITLE
Allow YAML or JS format for configuration file

### ISSUE THREAD

**Issue by mathieu-bour** [smeijer/unimported#118]
My application is using the `@uniswap/widgets` package which for some reason does not install the necessary packages by himself and I add to install some dependencies manually.

This is my current configuration:

```json
{
  "entry": [
    "src/pages/**/*.page.{ts,tsx}",
    "src/worker/index.ts",
    "next.config.js",
    "cypress/e2e/*.cy.ts",
    "cypress/support/e2e.ts"
  ],
  "ignorePatterns": ["**/node_modules/**", "public/**"],
  "ignoreUnimported": ["src/icons/IconTemplate.js"],

  "__note": "@ethersproject/abi jotai-immer are required by @uniswap/widgets",
  "ignoreUnused": ["next", "react", "react-dom", "@ethersproject/abi", "jotai-immer"],
  "ignoreUnresolved": ["tslib", "cross-fetch", "extract-files", "form-data"]
}
```

As you can see, there is a pseudo-comment explaining why I am ignoring `@ethersproject/abi` and `jotai-immer` packages.

I would like to be able to write the configuration file as a YAML file which will allow comments:

```yaml
entry:
- src/pages/**/*.page.{ts,tsx}
- src/worker/index.ts
- next.config.js
- cypress/e2e/*.cy.ts
- cypress/support/e2e.ts
ignorePatterns:
- "**/node_modules/**"
- public/**
ignoreUnimported:
- src/icons/IconTemplate.js

ignoreUnused:
- next
- react
- react-dom
# Required by @uniswap/widgets
- "@ethersproject/abi"
- jotai-immer

ignoreUnresolved:
- tslib
- cross-fetch
- extract-files
- form-data
```

Happy to open a PR if interested.
